baseURL: "https://blog.tylerhou.io/"
languageCode: "en-us"
title: "Tyler Hou"
theme: "tylerhou"

params:
  dateformat: "_2 Jan 2006"
  author:
    name: "Tyler Hou"
    occupation: "Software Development Engineer"
    linkedin: "https://www.linkedin.com/in/tylerhou"
    resume:
      pdf: "/resume.pdf"
      tex: "/resume.tex"
